#############################
# Builder for Windows
#############################
FROM golang:1.25 AS builder-windows

# Set environment variables for Windows
ENV GOARCH=amd64
ENV GOOS=windows

WORKDIR /app

# Copy Go module files first (cache optimization)
COPY go.mod go.sum ./

# Use CMD instead of PowerShell
RUN cmd /C "go mod download"

# Copy the Go source code
COPY . .

# Build the Windows binary using CMD
RUN cmd /C "go build -o 3270Connect.exe ."
