#############################
# Linux Dockerfile
#############################
FROM golang:1.25 AS builder-linux

# Set environment variables for Linux
ENV GOARCH=amd64
ENV GOOS=linux

WORKDIR /app

# Copy Go module files first (cache optimization)
COPY go.mod go.sum ./
RUN go mod download

# Copy the Go source code
COPY . .

# Build the Linux binary
RUN go build -o 3270Connect-linux .

#############################
# Final stage for Linux
#############################
FROM alpine:latest AS final-linux

# Copy the Linux binary from the builder
COPY --from=builder-linux /app/3270Connect-linux /usr/local/bin/3270Connect

# Make the binary executable
RUN chmod +x /usr/local/bin/3270Connect

# Define the entrypoint for the Linux container
ENTRYPOINT ["/usr/local/bin/3270Connect"]
