site_name: 3270Connect
site_description: User Guide for the 3270Connect Command-Line Utility
site_author: Jnnngs
site_url: https://3270.io
repo_url: https://github.com/3270io/3270Connect
#edit_uri: edit/master/docs/
docs_dir: docs
theme:
  name: material

nav:
  - Welcome: index.md
  - Installation: installation.md
  - Basic Usage: basic-usage.md
  - Advanced Features: advanced-features.md

plugins:
  - search
  - mkdocs-video:
      is_video: True
      video_autoplay: False
markdown_extensions:
  - codehilite:
      guess_lang: false

extra:
  version: 1.0.0
