# This workflow will build a Golang project for both Linux and Windows
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build for Linux
      run: go build -v -o 3270Connect ./...

    - name: Test
      run: go test -v ./...

    - name: Upload Linux Binary
      uses: actions/upload-artifact@v3
      with:
        name: 3270Connect-linux
        path: 3270Connect

  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build for Windows
      run: go build -v -o 3270Connect.exe ./...

    - name: Test
      run: go test -v ./...

    - name: Upload Windows Binary
      uses: actions/upload-artifact@v3
      with:
        name: 3270Connect-windows
        path: 3270Connect.exe
